[tool.poetry]
name = "lx-music-api-server-python"
version = "2.0.0.beta-10"
description = "一个适配 LX Music 的 API 后端实现"
authors = ["helloplhm-qwq", "lerdb", "Folltoshe"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
aiohttp = "^3.9.3"
pycryptodome = "^3.20.0"
ujson = "^5.9.0"
requests = "^2.31.0"
colorlog = "^6.8.2"
Pygments = "^2.17.2"
xmltodict = "^0.13.0"
pillow = "^10.2.0"
mutagen = "^1.47.0"
colorama = "^0.4.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
